### ISSUE TITLE
Cannot read property 'getElementById' of undefined

### ISSUE THREAD

**Issue by luisenriqueramos1977** [apache/incubator-echarts#12916]
### Version
4.8.0

### Steps to reproduce
1. edit index.js
2. paste example 1 from https://echarts.apache.org/en/tutorial.html#ECharts%20Basic%20Concepts%20Overview
3. Error

### What is expected?
a graph according to example

### What is actually happening?
var myChart = echarts.init(document.getElementById('main'));
                           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/home/lsrs/Desktop/jsexercise/egraphtest/index.js:6:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

[Done] exited with code=1 in 0.699 seconds

---
I  included the code: 

var document = document.getElementById('dom-id');

and appeared the new error:

var document = document.getElementById('dom-id');
                        ^

TypeError: Cannot read property 'getElementById' of undefined
    at Object.<anonymous> (/home/lsrs/Desktop/jsexercise/egraphtest/index.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by plainheart** [comment]
I think there may be missing some detailed information.
1) What does your source code like?
2) Are there some grammar or usage errors in your source code?

**Comment by luisenriqueramos1977** [comment]
Dear Wang,

thanks for your quick response, the code I using is exactly the one it is
published in this source

https://echarts.apache.org/en/tutorial.html#Use%20ECharts%20with%20webpack

this is the code:

var echarts = require('echarts'); // initialize echarts instance with
prepared DOM var myChart = echarts.init(document.getElementById('main')); //
draw chart myChart.setOption({ title: { text: 'ECharts entry example' },
tooltip: {}, xAxis: { data: ['shirt', 'cardign', 'chiffon shirt', 'pants',
'heels', 'socks'] }, yAxis: {}, series: [{ name: 'sales', type: 'bar', data:
[5, 20, 36, 10, 10, 20] }] });


Until now, I have not been able to run any example, all generate errors.


Luis Ramos

**Comment by plainheart** [comment]
This code looks like no problem. I'm afraid this error is related to the environment of your project, please ensure whether `document` or `window` exists and is able to be fetched.

**Comment by luisenriqueramos1977** [comment]
I think I included document as follows:
var document = document.getElementById('dom-id');

and later got this error:

var myChart = echarts.init(document.getElementById('main'));
                                    ^

TypeError: Cannot read property 'getElementById' of undefined
    at Object.<anonymous> (/home/lsrs/Desktop/jsexercise/egraphtest/index.js:6:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

[Done] exited with code=1 in 0.693 seconds


Until now, I have not been able to run any example, and I feel frustrated.

**Comment by luisenriqueramos1977** [comment]
The only thing I did was install according instructions
npm install echarts --save, in vs code. 

many erros for missing package were produced, but I only had to install packages, and finally run with errors. I attached the view of my environment

![image](https://user-images.githubusercontent.com/48624384/86575271-481b8d00-bf77-11ea-9e77-938316e1f635.png)

**Comment by plainheart** [comment]
It needs a HTML but not just run `index.js`, `document` can't be fetched in node env.

**Comment by luisenriqueramos1977** [comment]
okay,

I finally got one working,

https://echarts.apache.org/en/tutorial.html#Create%20Custom%20Build%20of%20ECharts

I have to remark, that I changed the code for this:

*<script src="lib/echarts.custom.js"></script> *

to this

<script src="lib/echarts.custom.min.js"></script>


It was open with live server in vs code


I will continue with other exercises


Luis

**Comment by plainheart** [comment]
I'm still confused about this, but anyway, I'm glad it works for you now.
