### ISSUE TITLE
Uncaught TypeError: Cannot read property 'eachComponent' of undefined

### ISSUE THREAD

**Issue by yangqinjiang** [apache/incubator-echarts#6289]
### One-line summary [问题简述]

all.echarts.min.js:35 Uncaught TypeError: Cannot read property 'eachComponent' of undefined
    at Object.action (http://test.com/Public/js/all.echarts.min.js:35:23326)
    at a.<anonymous> (http://test.com/Public/js/all.echarts.min.js:1:6520)
    at Array.forEach (native)
    at f (http://test.com/Public/js/all.echarts.min.js:1:2106)
    at a.l (http://test.com/Public/js/all.echarts.min.js:1:6500)
    at a.Q.dispatchAction (http://test.com/Public/js/all.echarts.min.js:10:5500)
    at http://test.com/Public/Statistics/js/substation_map_chart_2.js?ssssss:592:26

图表示例: http://echarts.baidu.com/gallery/editor.html?c=scatter-map-brush

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
具体描述你的代码和环境，贴出详细复现的方式

**Comment by winterZhao** [comment]
chrome 版本 87.0.4280.14
echarts 5.0.0
在柱状图、平行坐标系等多种图表上点击后会碰到这样的问题

dataSelectAction.js?2e4d:67 Uncaught TypeError: Cannot read property 'eachComponent' of undefined
    at handleSeriesLegacySelectEvents (dataSelectAction.js?2e4d:67)
    at MessageCenter.eval (dataSelectAction.js?2e4d:93)
    at MessageCenter.Eventful.trigger (Eventful.js?6903:103)
    at ECharts.doDispatchAction (echarts.js?e9ea:1265)
    at ECharts.dispatchAction (echarts.js?e9ea:831)
    at Handler.eval (echarts.js?e9ea:1324)
    at Handler.Eventful.trigger (Eventful.js?6903:103)
    at Handler.dispatchToElement (Handler.js?3a5d:146)
    at Handler.<computed> [as click] (Handler.js?3a5d:221)
    at HandlerDomProxy.Eventful.trigger (Eventful.js?6903:103)
