### ISSUE TITLE
保存图片错误

### ISSUE THREAD

**Issue by bxsw** [apache/incubator-echarts#8803]
### One-line summary [问题简述]
图表中symbol配置项用到以URL方式提供的资源时，保存为图片时报错
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Gr.OI.getDataURL (/js/echarts.min.js:22:328007)
    at Gr.OI.getConnectedDataURL (/js/echarts.min.js:22:328707)
    at Aa.getConnectedDataURL (/js/echarts.min.js:22:2321)
    at Qy.onclick (/js/echarts.min.js:22:680232)
    at In.<anonymous> (/js/echarts.min.js:22:2321)
    at In.trigger (/js/echarts.min.js:22:226239)
    at L_.dispatchToElement (/js/echarts.min.js:22:228282)
    at L_.(anonymous function) [as click] (/js/echarts.min.js:22:229119)
    at xi.trigger (/js/echarts.min.js:22:226239)
    at xi.Uw.(anonymous function) (/js/echarts.min.js:22:269341)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
ECharts 4.1
Chrome  67.0.3396.99
Windows 10

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'none'
        },
        formatter: function (params) {
            return params[0].name + ': ' + params[0].value;
        }
    },
    toolbox:{
        feature:{
            saveAsImage:{}
        }
    },
    xAxis: {
        data: ['驯鹿', '火箭', '飞机', '高铁', '轮船', '汽车', '跑步', '步行', ],
        axisTick: {show: false},
        axisLine: {show: false},
        axisLabel: {
            textStyle: {
                color: '#e54035'
            }
        }
    },
    yAxis: {
        splitLine: {show: false},
        axisTick: {show: false},
        axisLine: {show: false},
        axisLabel: {show: false}
    },
    color: ['#e54035'],
    series: [{
        name: 'hill',
        type: 'pictorialBar',
        barCategoryGap: '-130%',
        symbol: 'image://http://imgsrc.baidu.com/forum/pic/item/a985b831ddbf294442a75bbd.jpg',
        itemStyle: {
            normal: {
                opacity: 0.5
            },
            emphasis: {
                opacity: 1
            }
        },
        data: [123, 60, 25, 18, 12, 9, 2, 1],
        z: 10
    }, {
        name: 'glyph',
        type: 'pictorialBar',
        barGap: '-100%',
        symbolPosition: 'end',
        symbolSize: 50,
        symbolOffset: [0, '-120%'],
        data: [{
            value: 123,
            symbolSize: [60, 60]
        }, {
            value: 60,
            symbolSize: [50, 60]
        }, {
            value: 25,
            symbolSize: [65, 35]
        }, {
            value: 18,
            symbolSize: [50, 30]
        }, {
            value: 12,
            symbolSize: [50, 35]
        }, {
            value: 9,
            symbolSize: [40, 30]
        }, {
            value: 2,
            symbolSize: [40, 50]
        }, {
            value: 1,
            symbolSize: [40, 50]
        }]
    }]
};

```

**Comment by pissang** [comment]
因为你用到了跨域的图片，需要把图片保存到你自己的服务器中
